version: "3.8"
 
services:
  chef:
    build: .
    container_name: chef
    # restart: always
    #   - secret.dev.env
    ports:
      - 1882:1882
    environment:
        BASE_DIR: /home/pdi
    volumes:
      - ./jobs:/home/pdi/jobs
