version: "3.8"
 
services:
  cube:
    image: chef:latest
    container_name: chef
    # restart: always
    #   - secret.dev.env
    ports:
      - 1882:1882
    environment:
        BASE_DIR: /pdiserver
    volumes:
      - ./jobs:/pdiserver/jobs
